apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: demo-spring-boot-automation
  namespace: flux-system
spec:
  interval: 1m
  update:
    strategy: Setters
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: "flux-system"
        email: "flux@system.com"
    push:
      branch: main
  imageRepositoryRef:
    name: demo-spring-boot-image
