apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: demo-spring-boot-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: demo-spring-boot-image
  policy:
    semver:
      range: '1.x.x'  # Define which version range should be used.
