apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-spring-boot
  namespace: flux-system
spec:
  interval: 1m
  path: "./manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: demo-spring-boot
  images:
    - name: demo-spring-boot
      newName: docker.io/jish65/demo-spring-boot
      newTag: 'latest'  # Update this tag as needed.
