apiVersion: v1
kind: Service
metadata:
  name: demo-spring-boot-service
  namespace: default  # Update to default if that's your desired namespace
spec:
  selector:
    app: demo-spring-boot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
